### ISSUE TITLE
Error in this App

### ISSUE THREAD

**Issue by andreakoelzsch** [bart1/Movebank-Data-Repository-App#1]
Hi Bart,

We have finally managed to have your App integrated also as starting App in MoveApps, maybe have a look if you have time ;) 

However, I now get the below error for also the default doi, do you have any idea?

Error in checkSlotAssignment(object, name, value): assignment of an object of class “numeric” is not valid for slot ‘timestampsUnUsedRecords’ in an object of class “.unUsedRecords”; is(value, ".OptionalPOSIXct") is not TRUE

Thanks!
Andrea

**Comment by bart1** [comment]
It this within moveApps or on your dektop, for me everything seems to work fine on moveapps

**Comment by bart1** [comment]
I just had an example workflow running and tried to publish it, let me know if that fails for you. Please note some datasets do not convert as the data in the data repository is not very standardized/has various filtering applied (e.g. some have duplicated locations usw)

**Comment by andreakoelzsch** [comment]
Hi Bart, It was on moveapps that the app failed. A shared WF would be great. Please dont use publish there, but share. And share it with me only (Nickname: andreakoelzsch), then not everybody gets it. Please can you try? Thanks!

**Comment by andreakoelzsch** [comment]
Correction. The App by itself works (sorry), but the integration with data coming from an App before it, gives the error..

**Comment by bart1** [comment]
Ah that sounds like a movestack error. Maybe you can give the two dois so we can reproduce locally I guess this is more broad then only the app but rather a move issue

**Comment by bart1** [comment]
I should now have shared a working example

**Comment by andreakoelzsch** [comment]
I can share the workflow with you on MoveApps, then you have all info, ok?

**Comment by bart1** [comment]
Where do I find sharred workflows ?

**Comment by andreakoelzsch** [comment]
I did receive your workflow in MoveApps, and indeed it works nicely, thanks! Combining data from the Movebank App and the Movebank Repository App seems to be a problem.. see my shared WF with you

**Comment by andreakoelzsch** [comment]
the shared WFs should pop up just above the list of public WFs in the WF overview

**Comment by bart1** [comment]
Ok I have it now, ps would making one of these workflows public maybe be useful communicate the moveapps capabilites, its is basically quicker and easier to get started with testing data compared to the movebank api. It seems useful for first time users and education a

**Comment by andreakoelzsch** [comment]
yes, good idea. I have to leave now picking up the kids. Lets continue on this tomorrow. tahnks!

**Comment by bart1** [comment]
Should be fixed with the next move release (and rebuild of the app afterwards): https://gitlab.com/bartk/move/-/commit/0c2b83bb417a2c9b2fd3545b6c8eee4f3d320367
