### ISSUE TITLE
deprecate? or add warning message

### ISSUE THREAD

**Issue by annescharf** [bart1/Movebank-Data-Repository-App#4]
Hi @bart1, given that this app is nor working anymore, it might be good to either deprecate it or at least write a warning note that it is currently not working (go to "my apps", open the app, top right "edit details", or "deprecate" button). Thanks!

**Comment by andreakoelzsch** [comment]
@bart1 Hi Bart, please can you deprecate the App? Does not take long, but we cannot do it, sorry: https://docs.moveapps.org/#/app_deprecation Thanks!
